#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || polybar --reload main > /var/log/polybar.log 2>&1 &
pgrep -x picom > /dev/null || picom --experimental-backends --log-level=DEBUG > /var/log/picom.log 2>&1 &
xmodmap ~/.Xmodmap &
xsetroot -cursor_name left_ptr &
feh --bg-scale ~/pics/wallpapers/wallhaven-o3xrm9.jpg &

# Configure workspaces
# NOTE: When changing HDMI ports configuring the monitor breaks
# TODO: Detect monitor programmatically
bspc monitor HDMI-A-0 -d misc dev www im email other

bspc config border_width 2
bspc config window_gap   5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Send programs to theme desktops
bspc rule -a firefox desktop=^3
bspc rule -a Mailspring desktop=^5
bspc rule -a Slack desktop=^4
bspc rule -a "Microsoft Teams - Preview" desktop=^4
bspc rule -a Bitwarden desktop=^6
